export const GET_FLIGHTS_REQUEST = 'GET_FLIGHTS_REQUEST';
export const GET_FLIGHTS_FAILURE = 'GET_FLIGHTS_FAILURE';
export const GET_FLIGHTS_SUCCESS = 'GET_FLIGHTS_SUCCESS';

export const GET_NAMES_REQUEST = 'GET_NAMES_REQUEST';
export const GET_NAMES_FAILURE = 'GET_NAMES_FAILURE';
export const GET_NAMES_SUCCESS = 'GET_NAMES_SUCCESS';

export const CHANGE_SELECT_VALUE = 'CHANGE_SELECT_VALUE';
